import type { DemoState,Visit } from "./domain";
export type ServiceResult<T>={ok:true;value:T}|{ok:false;code:string};
export function resolveInvitation(state:DemoState,token:string,now=new Date()):ServiceResult<Visit>{const v=state.visits.find(x=>x.invitationToken===token);if(!v)return {ok:false,code:"invalid"};if(v.status==="cancelled")return {ok:false,code:"cancelled"};if(new Date(v.endsAt).getTime()+864e5<now.getTime())return {ok:false,code:"expired"};return {ok:true,value:v}}
export function resolveQr(state:DemoState,token:string,now=new Date()):ServiceResult<{visit:Visit;window:"valid"|"outside"}>{const v=state.visits.find(x=>x.qrToken===token);if(!v)return {ok:false,code:"invalid"};if(["cancelled","expired","denied"].includes(v.status))return {ok:false,code:v.status};const start=new Date(v.startsAt).getTime()-15*60000,end=new Date(v.endsAt).getTime()+30*60000;return {ok:true,value:{visit:v,window:now.getTime()>=start&&now.getTime()<=end?"valid":"outside"}}}
export function checkIn(visit:Visit,at=new Date(),allowOutside=false):ServiceResult<Visit>{if(visit.status==="checked_in")return {ok:false,code:"duplicate_check_in"};if(["checked_out","cancelled","expired","denied"].includes(visit.status))return {ok:false,code:"invalid_status"};const valid=at.getTime()>=new Date(visit.startsAt).getTime()-15*60000&&at.getTime()<=new Date(visit.endsAt).getTime()+30*60000;if(!valid&&!allowOutside)return {ok:false,code:"outside_window"};return {ok:true,value:{...visit,status:"checked_in",checkedInAt:at.toISOString()}}}
export function checkOut(visit:Visit,at=new Date()):ServiceResult<Visit>{if(visit.status==="checked_out")return {ok:false,code:"duplicate_check_out"};if(visit.status!=="checked_in")return {ok:false,code:"not_checked_in"};return {ok:true,value:{...visit,status:"checked_out",checkedOutAt:at.toISOString()}}}
export function revokeQr(visit:Visit):Visit{return {...visit,qrToken:undefined}}
export function createManualVisit(input:Pick<Visit,"visitorName"|"email"|"company"|"hostName"|"hostId"|"location"|"purpose">,at=new Date()):Visit{return {...input,id:crypto.randomUUID(),startsAt:at.toISOString(),endsAt:new Date(at.getTime()+3600000).toISOString(),checkedInAt:at.toISOString(),status:"checked_in",origin:"guard_manual",documentCaptured:false,consentedAt:at.toISOString()}}
export function expiredDocumentIds(documents:Array<{id:string;retentionExpiresAt:string;deletedAt?:string}>,now=new Date()){return documents.filter(d=>!d.deletedAt&&new Date(d.retentionExpiresAt)<=now).map(d=>d.id)}
