"use client";
import Link from "next/link"; import { useDemo } from "./demo-provider"; import { Activity,ArrowUpRight,CalendarDays,Clock3,LogIn,LogOut,ShieldX,Users } from "lucide-react"; import { Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts"; import { StatusPill } from "./status-pill";
const fmt=(v:string)=>new Intl.DateTimeFormat("es-MX",{hour:"2-digit",minute:"2-digit"}).format(new Date(v));
export function Dashboard(){const {state}=useDemo();const today=new Date().toDateString();const todayVisits=state.visits.filter(v=>new Date(v.startsAt).toDateString()===today);const inside=state.visits.filter(v=>v.status==="checked_in");const completed=state.visits.filter(v=>v.status==="checked_out");const denied=state.visits.filter(v=>v.status==="denied");const avg=completed.length?Math.round(completed.reduce((a,v)=>a+((new Date(v.checkedOutAt!).getTime()-new Date(v.checkedInAt!).getTime())/60000),0)/completed.length):0;
 const chart=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);const same=state.visits.filter(v=>new Date(v.startsAt).toDateString()===d.toDateString());return {day:new Intl.DateTimeFormat("es-MX",{weekday:"short"}).format(d),entradas:same.filter(v=>["checked_in","checked_out"].includes(v.status)).length,salidas:same.filter(v=>v.status==="checked_out").length}});
 const cards=[["Programadas hoy",todayVisits.length,CalendarDays,"text-blue-600 bg-blue-50"],["Personas dentro",inside.length,Users,"text-emerald-600 bg-emerald-50"],["Salidas",completed.filter(v=>new Date(v.checkedOutAt!).toDateString()===today).length,LogOut,"text-indigo-600 bg-indigo-50"],["Rechazadas",denied.length,ShieldX,"text-red-600 bg-red-50"],["Duración promedio",`${avg||52} min`,Clock3,"text-amber-600 bg-amber-50"]] as const;
 return <><header className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-sm font-medium text-[#0eaaa5]">Jueves, 27 de agosto</p><h1 className="text-3xl font-semibold tracking-[-.03em]">Buenos días, Elena</h1><p className="mt-2 text-slate-500">Esto es lo que está pasando hoy en Nova Logistics.</p></div><Link href="/app/visits/new" className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-[#071426] px-5 text-sm font-semibold text-white hover:bg-[#102644]">Nueva invitación <ArrowUpRight size={17}/></Link></header>
 <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([label,value,Icon,color])=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className={`mb-4 grid size-10 place-items-center rounded-xl ${color}`}><Icon size={19}/></div><p className="text-2xl font-semibold">{value}</p><p className="mt-1 text-sm text-slate-500">{label}</p></div>)}</section>
 <section className="mt-6 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-6"><h2 className="font-semibold">Flujo semanal</h2><p className="text-sm text-slate-500">Entradas y salidas registradas</p></div><div className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="teal" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#10cfc9" stopOpacity={.35}/><stop offset="1" stopColor="#10cfc9" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e8edf4"/><XAxis dataKey="day" axisLine={false} tickLine={false}/><YAxis allowDecimals={false} axisLine={false} tickLine={false}/><Tooltip/><Area dataKey="entradas" type="monotone" stroke="#10aaa5" fill="url(#teal)" strokeWidth={2}/><Area dataKey="salidas" type="monotone" stroke="#2563eb" fill="transparent" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></div>
 <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-semibold">Próximas visitas</h2><p className="text-sm text-slate-500">Agenda inmediata</p></div><Activity size={19} className="text-slate-400"/></div><div className="space-y-1">{state.visits.filter(v=>new Date(v.startsAt)>new Date()).slice(0,5).map(v=><Link href={`/app/visits/${v.id}` as never} key={v.id} className="flex items-center gap-3 rounded-xl p-3 hover:bg-slate-50"><span className="grid size-10 place-items-center rounded-full bg-slate-100 text-sm font-semibold">{v.visitorName.split(" ").map(x=>x[0]).slice(0,2)}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{v.visitorName}</span><span className="block truncate text-xs text-slate-500">{v.hostName} · {fmt(v.startsAt)}</span></span><StatusPill status={v.status}/></Link>)}</div></div></section>
 <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-5 flex items-center justify-between"><h2 className="font-semibold">Actividad reciente</h2><Link href="/app/visits" className="text-sm font-medium text-blue-600">Ver todo</Link></div><div className="grid gap-3 md:grid-cols-2">{state.events.slice(0,6).map(e=>{const v=state.visits.find(x=>x.id===e.visitId);return <div key={e.id} className="flex items-center gap-3 rounded-xl border border-slate-100 p-3"><span className="grid size-9 place-items-center rounded-full bg-cyan-50 text-cyan-700">{e.type==="check_in"?<LogIn size={16}/>:<CalendarDays size={16}/>}</span><div><p className="text-sm font-medium">{v?.visitorName}</p><p className="text-xs text-slate-500">{e.actor} · {fmt(e.at)}</p></div></div>})}</div></section></>}
